### PR TITLE
Chinese version of the "Why Isn’t X a Hook?" post

### PR DESCRIPTION
**Pull request by RetroAstro**
The Chinese translation of "Why Isn’t X a Hook?"

### CODE REVIEW

**Comment by zhongdeming428** [comment]
https://github.com/gaearon/overreacted.io/pull/213/files

U two translated the same article to Simplified-Chinese~

**Comment by xueqingxiao** [comment]
@zhongdeming428 repetitive work.
@RetroAstro I think we should cooperate. trying to translate diff post and review each other.

**Comment by xueqingxiao** [comment]
@RetroAstro same as GitHub id: xueqingxiao

**Comment by gaearon** [comment]
I just merged https://github.com/gaearon/overreacted.io/pull/213. Can you please update this so it's only another page? I'd also prefer to only merge full translations. Thanks.

**Comment by RetroAstro** [comment]
@gaearon Sorry, I started translating another post "React as a UI runtime" a few days ago, I will finish this today 😂.

**Comment by RetroAstro** [comment]
And I will only commit the "React as a UI runtime" post this time 😂.

**Pull request closed without merging**
