### PR TITLE
Update i18n.js

### PR DESCRIPTION
**Pull request by TheBrown**
Add Laos font. Laos is between Thailand and Vietnam

### CODE REVIEW

**Comment by gaearon** [comment]
I don't think we have a single `lo` translation yet? Let's add when we have one.

**Comment by TheBrown** [comment]
I'll upload my `lo` file. any advice for contribution, please :)

**Comment by gaearon** [comment]
Advice on what?

**Comment by TheBrown** [comment]
On translation. I see the instruction they said it should has the `lo` first in the list

**Comment by sterekai** [comment]
After you have translated an article, add a file called `index.lo.md` to the directory of the article you have translated. For example: `src/pages/optimized-for-change/index.lo.md`.

If your language isn't defined in the language object, the application will raise an error. That's why you had to edit the `i18n.js` file.

**Comment by TheBrown** [comment]
Thank you @sterekai

**Pull request closed without merging**
