### PR TITLE
Translate to Portuguese: How Are Function Components Different from…

### PR DESCRIPTION
**Pull request by cesarwbr**
This pull request contains a translation of the article How Are Function Components Different from Classes? to Portuguese.

### CODE REVIEW

**Comment by gaearon** [comment]
You'll need to add `pt` here: https://github.com/gaearon/overreacted.io/blob/master/i18n.js

**Comment by Luanf** [comment]
Actually, it seems to me the translation is in pt-br (which is already added to the i18n file)
@cesarwbr check out your file name, you need to change that to the pt-br pattern.
I can review your text later when I have some time (if no one does it until then) :+1:

**Comment by cesarwbr** [comment]
@gaearon I changed the file name. Thanks @Luanf !

**Comment by gaearon** [comment]
Thank you!

**Pull request merged**
