### PR TITLE
Semantic fix

### PR DESCRIPTION
**Pull request by amcsi**
This is not a grammatical correction, but a semantic one. I believe this is what is correct.
Although I might be changing the effect of what you're saying won't be quite as good this way, so feel free to change the text completely.

Amazing article by the way :) it's just this one bit that I think should be fixed before I would be happy to share it.

### CODE REVIEW

**Comment by gaearon** [comment]
Well.. both of these are true, depending on what precisely you want to illustrate.

**Comment by amcsi** [comment]
@gaearon Please reconsider and read again what you wrote. This is what you wrote:

> ...the `prototype` property of a class or a function _does not_ point to the prototype of that value.

```js
function Person() {}
Person.prototype.foo = 'bar';

Person.prototype !== Person.prototype;
// ^ it appears like with your sentence you are claiming this to be true.
```

And in your example code you wrote:

```js
console.log(Person.prototype); // 🤪 Not Person's prototype
```

But yes, `Person.prototype` is `Person`'s prototype.

**Comment by gaearon** [comment]
I understand what I wrote.  :-)

If by "X's prototype" you mean "next value in the prototype chain of X" (which is how a lot of people interpret it) then no, `Person.prototype` is not `Person`'s prototype. `Person`'s prototype is `Person.__proto__` (which is `Function.prototype`). This is how `Person` gets function "methods" like `bind`.

Now, of course, this part is not relevant to instances of `Person`. That's the other side of this confusion that you're trying to illustrate.

**Comment by amcsi** [comment]
I see what you're saying now. Wow that really is confusing. Basically when someone says "a function's prototype", it could mean that function's "prototype" property _or_ it could mean that function's (_as an instance_) prototype (which is always the global `Function` function's prototype).

```js
(function () {}).__proto__ === Function.prototype
```

I kind of feel like it's not that useful to mention this though, because I believe the confusion with prototypes have more to do with understanding the prototypal relationship between a newed instance and its function/class. But anyway, this is your article!

**Pull request closed without merging**
