### PR TITLE
Add specific index page for each language that has a translated article

### PR DESCRIPTION
**Pull request by AlexRobinson-**
Hey!

I saw this issue https://github.com/gaearon/overreacted.io/issues/131 (Add language pages) and thought I would have a poke at it.

Any suggestions are welcome, and if you don't think this solution fits what you were thinking of, feel free to close the PR!

### Downsides of my PR:
* It would be nice to have the new text "The following are community provided translations" translate-able as well. But since there wasn't any support for translating specific text on the website that at the moment I decided to ignore it for this PR
* I had to create a new `./i18n.js` file so the node app could load in the languages the blog supports, so now there are two i18n files ¯\\_(ツ)_/¯

### What it looks like
overreacted v3

### CODE REVIEW

**Comment by tdd** [comment]
@AlexRobinson- this is a very nice start (I'm also looking into a way for random text to be translatable, so article pages have a more homogeneous translated feel).

What I'm wondering is: should the per-locale listings act as a variant or the main listing, and still list untranslated articles in their proper (reverse-chronological) positions? Or should they be clearly identified as a subset (which probably needs some intro text at the top stating that there may be other, untranslated articles, that links back to the root page)?

@gaearon any thoughts on this?

**Comment by AlexRobinson-** [comment]
@tdd Thanks for checking out the PR!

> What I'm wondering is: should the per-locale listings act as a variant or the main listing

I'm personally a huge fan of this. While hacking away at this, I envisaged the home page providing an option to switch locale - which would update the language for the whole site. Meaning it would all be the same home page - just in a different language (and a notice about community provided translations.

> and still list untranslated articles in their proper (reverse-chronological) positions? Or should they be clearly identified as a subset (which probably needs some intro text at the top stating that there may be other, untranslated articles, that links back to the root page)?

My original idea for the translated home page was to display all of the articles. For the ones that aren't translated it would still show the non-translated version but with less prominent visuals. Something like slightly graying it out? Though I'm not 100% convinced.

For now I went with the small notice "The following are community provided translations" (which would ideally also be translated). But I agree some better wording + extra information about the fact this is most likely only a subset of all of the articles and linking back to the original home page would be great

**Comment by tdd** [comment]
@AlexRobinson- personally I love the idea of keeping the entire article listing (well, the exact same one as the root page anyway) but using slightly-less-prominent styling (e.g. mid-gray) for untranslated articles.

OTOH, I dislike the idea of a single root page for all locales, as this ruins bookmarking, sitemapping, and the like. We want to be able to take people to specific locales, to have statically-rendered versions of all pages with proper `lang=` attributes etc.

An open question would be: does the canonical root page feature some sort of link / dropdown to the per-locale listings? That'd be nice. A flat listing would quickly be too obtrusive, but some fixed-space access would be neat.

**Comment by AlexRobinson-** [comment]
@tdd I absolutely agree with having seperate urls for each locale's home page 😄

For the slightly less prominent styling I'm keen to have a play at what that could look like, but the reason I'm not 100% convinced, is for locales where maybe only one or two articles are translated out of 20+ I don't think it would be the best user experience to have to scroll through articles trying to find the one or two that are translated.

Which does raise another idea - should there then be a toggle to hide/show untranslated articles when viewing a locale's listings? I feel that it may just add complexity and too many options though.

> An open question would be: does the canonical root page feature some sort of link / dropdown to the per-locale listings? That'd be nice. A flat listing would quickly be too obtrusive, but some fixed-space access would be neat.

I'm 100% in favour of a link/dropdown that will take the user to the specific index page for a locale. A good place for it to live could be next to the current theme toggle?

@tdd @gaearon what are your thoughts on merging in something minimal like this PR in its current state that just adds a link to view locale specific articles that looks similar to the root page?
We could then create new issues for implementing the locale dropdown + showing all listings on the locale specific index page.

**Comment by gaearon** [comment]
Thanks

**Comment by gaearon** [comment]
Starting the dev server recently got very slow. I wonder if it's due to this change? Could you look at what can be optimized?

**Comment by tdd** [comment]
My money's on every locale re-calling the API to get all articles then filtering (and generally duplicating API calls).

The main node script should fetch first then call each locale index with a prefiltered list of posts.

**Comment by cosmopeon** [comment]
#286

**Pull request merged**
