### PR TITLE
Fix typos: was => were (unreal conditional sentence), remove extra "be"

### PR DESCRIPTION
**Pull request by latema**
Thanks for the excellently written article!

### CODE REVIEW

**Comment by j-f1** [comment]
The original reads better to me.

**Comment by latema** [comment]
> The original reads better to me.

I assume you mean the "was" vs. "were" and not the double "be"? Could you explain why the original reads better? It's clear to me that in this case "were" is correct, countless examples can be found easily. See for example https://www.grammarly.com/blog/was-vs-were/.

**Comment by j-f1** [comment]
I’m not really sure why it read better to me. Thanks for showing me that article — it taught me something new about English.

**Comment by latema** [comment]
I think it's because use of "was" is so widespread for this particular use case, all over in popular culture especially.

**Comment by gaearon** [comment]
Sure, thanks.

**Pull request merged**
