### PR TITLE
Fix a small grammar typo

### PR DESCRIPTION
**Pull request by mingaldrichgan**

### CODE REVIEW

**Comment by jackwilsdon** [comment]
I think "hot reloading functions doesn't" is more grammatically accurate than "hot reloading functions don't".

**Comment by mingaldrichgan** [comment]
I don't think "hot reloading functions doesn't" is grammatically accurate, but perhaps "the hot loading function doesn't"?

**Comment by jackwilsdon** [comment]
I believe it's referring to the hot reloading of functions themselves, not a function (or set of functions) which perform hot reloading, so in this case "hot reloading [of] functions doesn't work" makes sense (the "of" can be omitted and it's still clear to me).

**Comment by mingaldrichgan** [comment]
Ah I parsed it incorrectly before—my mistake! You're right, and it makes perfect sense now that I'm reading it correctly. (Personally, I think "hot reloading *of* functions" would be better for clarity but I'll close this pull request for now)

**Pull request closed without merging**
