### PR TITLE
Modification of french translation for optimized-for-change

### PR DESCRIPTION
**Pull request by Philmod**
cc @telaoumatenyanis 

Sorry for my tweet, I stumbled onto the screenshot because of the "gouffre du succès" which I couldn't understand without the link.

What do you think of those changes?

### CODE REVIEW

**Comment by telaoumatenyanis** [comment]
I understand what you mean. I chose "gouffre du succès" in order to keep the intended meaning, but I am open to any other translation.

Concerning **"memorable"**, I did not know if I should translate it using "mémorable" or "mémorisable". 

I looked at the other translations and apparently, they chose the "mémorable" meaning (e.g. : "Um bom design de API é **marcante** e claro" => marcante means "marquante"/"remarquable" here).

Either of them seems fine to me, "mémorisable" may even seem more natural here.

But I guess it depends on what @gaearon meant here. Does the API design makes it easy to remember, or does it leaves a lasting impression.

**Comment by gaearon** [comment]
I mean mostly "easy to remember". I think "memorable" can work like this in English but I don't know about other languages. "Memorizable" is closer in exact meaning but seems awkward in English.

**Comment by gaearon** [comment]
Seems okay to me

**Comment by telaoumatenyanis** [comment]
This pull request can be merged then.

Thank you @Philmod !

**Pull request merged**
