### PR TITLE
Update Bio.js from mobile Twitter link to main site

### PR DESCRIPTION
**Pull request by DanielAndrews43**

### CODE REVIEW

**Comment by sterekai** [comment]
[@gaearon's comment in #8:](https://github.com/gaearon/overreacted.io/issues/8#issuecomment-443566843)
> That's intentional — mobile website is desktop-friendly and will soon be the default one on desktop too. Also uses React.

**Comment by atomiks** [comment]
The web app appears to be default now for me

**Comment by sterekai** [comment]
@atomiks 

Interesting… Does Twitter redirect you to the mobile version on the desktop?

**Comment by gaearon** [comment]
They’re doing a gradual rollout.

**Pull request closed without merging**
