### PR TITLE
Russian translation of "Things I Don’t Know as of 2018"

### PR DESCRIPTION
**Pull request by Hopchenko**
Hi Dan, I've prepared Russian translation of "Things I Don’t Know as of 2018".

### CODE REVIEW

**Comment by Hopchenko** [comment]
Done

**Comment by Hopchenko** [comment]
I saw another one translation for this article, is it possible to store two versions of translation, so people can choose?

**Comment by gaearon** [comment]
To everyone who sent Russian translations — sorry it's taking me long to review. In this case I can't just go ahead and merge because I feel more responsible for being precise. I'll get back to these PRs once I have a bit of free time and maybe do some editing on top to set the right tone. I really appreciate them!

**Comment by Hopchenko** [comment]
@gaeron я так понимаю можно реквест закрывать? Переведу на украинский, как время будет)

**Comment by gaearon** [comment]
Да, я решил свои делать, тк хочу своим голосом. Украинский на основе русского звучит хорошо :-) Спасибо за потраченное время.

**Pull request closed without merging**
