### PR TITLE
Toggle checkbox display dark background for day mode too and redundancy of unit measure of 0px

### PR DESCRIPTION
**Pull request by dikshantpatodia**
In src/utils/global.css:

1. Mismatched property value for 'font-style'.
2. Line 60, font property font-family does not have generic default. Added sans-serif.

Logic issue:

1. Toggle checkbox display dark background for day mode too.

Fixes added in src/components/Toggle.js:

* a ternary condition for react-toggle-track.

Fixed added in src/components/Toggle.css

* added for-day and for-night classes to differentiate and added box-shadow to match the feel.

Unit issue in src/components/Toggle.css:
Issue: Unit of measure 'px' is redundant in Toggle.css

* Fixed by replacing 0px to 0.

### CODE REVIEW

**Comment by gaearon** [comment]
Please before/after screenshots for things that changed? Thanks.

**Comment by dikshantpatodia** [comment]
Wait sending the screenshot.

**Comment by dikshantpatodia** [comment]
after_indaymode
after_innightmode
before_indaymode
before_innightmode

**Comment by j-f1** [comment]
IMO this should be the other way around, with the toggle being black in the light theme and white in the dark theme, since it shows the background color for the theme that will be switched to. It also provides increased contrast.

**Comment by dikshantpatodia** [comment]
Its a good thought. Actually I wanted positive to remain positive and negative to remain negative, sun with a dark background doesn't make sense and moon with white.

**Comment by cosmopeon** [comment]
> sun with a dark background doesn't make sense and moon with white
Ok, let's leave it as is the case now, but change only background for sun

**Comment by gaearon** [comment]
Thanks, but I prefer the current version.

**Pull request closed without merging**
