### PR TITLE
WIP：translate: 'A Complete Guide to useEffect' into zh-hans

### PR DESCRIPTION
**Pull request by xueqingxiao**

### CODE REVIEW

**Comment by gaearon** [comment]
Note I made a few further changes in https://github.com/gaearon/overreacted.io/commit/d9a27d1f40fcee8c810bffde8faeca56b9160833.

**Comment by xueqingxiao** [comment]
@gaearon got it.

**Comment by gaearon** [comment]
Soo.. I just merged https://github.com/gaearon/overreacted.io/pull/407 and only later realized it duplicated your effort. I'm sorry about this.

@hzzheng Please check for existing PRs before sending a new one in the future. It's better to collaborate. I'll be more careful next time.

@xueqingxiao If you feel like @hzzheng's translation could be improved please still send a PR. I hope you two could collaborate in the future. Thank you both, and I'm sorry for mismanaging this.

**Comment by hzzheng** [comment]
sorry for that…I will be more careful in the future. We can collaborate to make it better！

**Pull request closed without merging**
